export const GET_AVAILABLE_TWITS = 'GET_AVAILABLE_TWITS';
export const FETCH_USERS_DATA = 'FETCH_USERS_DATA';
export const SAVE_USERS_DATA = 'SAVE_USERS_DATA';
export const FETCH_USERS_TWEETS = 'FETCH_USERS_TWEETS';
export const SAVE_USERS_TWEETS = 'SAVE_USERS_TWEETS';
